// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
  
  }

  interface StaticRouter {
    "/404": StaticRoute;
    "/451": StaticRoute;
    "/home": StaticRoute;
    "/": StaticRoute;
    "/position-managers/[[...slug]]": StaticRoute;
    "/terms-of-service": StaticRoute;
  }
}
