import { execSync } from "node:child_process"
import { Octokit } from "@octokit/rest"

export async function createPullRequest(token: string) {
  const status = execSync("git status --porcelain").toString().trim()
  if (!status) {
    console.log("No changes to commit")
    return
  }

  const timestamp = Date.now()
  const branch = `chore/i18n-bot-updates-${timestamp}`
  const title = "chore: Agent I18n Updates"
  const body = "Automated PR to update translation files generated by i18n bot."

  // Commit changes
  execSync('git config user.name "github-actions[bot]"')
  execSync(
    'git config user.email "github-actions[bot]@users.noreply.github.com"'
  )
  execSync(`git checkout -b ${branch}`)
  execSync("git add .")
  execSync(`git commit -m "${title}"`)

  const repoFull = process.env["GITHUB_REPOSITORY"]
  if (!repoFull) {
    throw new Error("GITHUB_REPOSITORY is not set")
  }
  const [owner, repo] = repoFull.split("/")

  // Push using the default GitHub token
  execSync(`git push origin ${branch}`)

  // Create PR with Octokit
  const octokit = new Octokit({ auth: token })
  const base = process.env["GITHUB_REF_NAME"] || "main"

  try {
    const { data } = await octokit.pulls.create({
      owner,
      repo,
      title,
      head: branch,
      base,
      body,
    })
    console.log(`✅ Pull request created: ${data.html_url}`)
  } catch (err: any) {
    console.error("❌ Failed to create PR:", err.response?.data || err.message)
    throw err
  }
}
